/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MembershipsRouteImport } from './routes/memberships'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FreeAuditRouteImport } from './routes/free-audit'
import { Route as DemosRouteImport } from './routes/demos'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CarePlansRouteImport } from './routes/care-plans'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalServiceAgreementRouteImport } from './routes/legal.service-agreement'
import { Route as LegalRefundRouteImport } from './routes/legal.refund'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckoutFailedRouteImport } from './routes/checkout.failed'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiTrackRouteImport } from './routes/api/track'
import { Route as ApiSendDocRouteImport } from './routes/api/send-doc'
import { Route as ApiQuoteRouteImport } from './routes/api/quote'
import { Route as ApiBlogPdfRouteImport } from './routes/api/blog-pdf'
import { Route as AdminTicketsRouteImport } from './routes/admin.tickets'
import { Route as AdminQuotesRouteImport } from './routes/admin.quotes'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminMembershipsRouteImport } from './routes/admin.memberships'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminInvoicesRouteImport } from './routes/admin.invoices'
import { Route as AdminCreditNotesRouteImport } from './routes/admin.credit-notes'
import { Route as AdminChatsRouteImport } from './routes/admin.chats'
import { Route as ApiYocoWebhookRouteImport } from './routes/api/yoco/webhook'
import { Route as ApiYocoCheckoutRouteImport } from './routes/api/yoco/checkout'
import { Route as ApiPayfastNotifyRouteImport } from './routes/api/payfast/notify'
import { Route as ApiPayfastCheckoutRouteImport } from './routes/api/payfast/checkout'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth/signup'
import { Route as ApiAdminCheckRoleRouteImport } from './routes/api/admin/check-role'
import { Route as ApiAdminBootstrapRouteImport } from './routes/api/admin/bootstrap'
import { Route as AdminTicketsIdRouteImport } from './routes/admin.tickets.$id'
import { Route as AdminQuotesIdRouteImport } from './routes/admin.quotes.$id'
import { Route as AdminLeadsIdRouteImport } from './routes/admin.leads.$id'
import { Route as AdminInvoicesIdRouteImport } from './routes/admin.invoices.$id'
import { Route as AdminCreditNotesIdRouteImport } from './routes/admin.credit-notes.$id'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipsRoute = MembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeAuditRoute = FreeAuditRouteImport.update({
  id: '/free-audit',
  path: '/free-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosRoute = DemosRouteImport.update({
  id: '/demos',
  path: '/demos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CarePlansRoute = CarePlansRouteImport.update({
  id: '/care-plans',
  path: '/care-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalServiceAgreementRoute = LegalServiceAgreementRouteImport.update({
  id: '/legal/service-agreement',
  path: '/legal/service-agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundRoute = LegalRefundRouteImport.update({
  id: '/legal/refund',
  path: '/legal/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutFailedRoute = CheckoutFailedRouteImport.update({
  id: '/checkout/failed',
  path: '/checkout/failed',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiTrackRoute = ApiTrackRouteImport.update({
  id: '/api/track',
  path: '/api/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendDocRoute = ApiSendDocRouteImport.update({
  id: '/api/send-doc',
  path: '/api/send-doc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuoteRoute = ApiQuoteRouteImport.update({
  id: '/api/quote',
  path: '/api/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogPdfRoute = ApiBlogPdfRouteImport.update({
  id: '/api/blog-pdf',
  path: '/api/blog-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotesRoute = AdminQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembershipsRoute = AdminMembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreditNotesRoute = AdminCreditNotesRouteImport.update({
  id: '/credit-notes',
  path: '/credit-notes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatsRoute = AdminChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AdminRoute,
} as any)
const ApiYocoWebhookRoute = ApiYocoWebhookRouteImport.update({
  id: '/api/yoco/webhook',
  path: '/api/yoco/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYocoCheckoutRoute = ApiYocoCheckoutRouteImport.update({
  id: '/api/yoco/checkout',
  path: '/api/yoco/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPayfastNotifyRoute = ApiPayfastNotifyRouteImport.update({
  id: '/api/payfast/notify',
  path: '/api/payfast/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPayfastCheckoutRoute = ApiPayfastCheckoutRouteImport.update({
  id: '/api/payfast/checkout',
  path: '/api/payfast/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCheckRoleRoute = ApiAdminCheckRoleRouteImport.update({
  id: '/api/admin/check-role',
  path: '/api/admin/check-role',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBootstrapRoute = ApiAdminBootstrapRouteImport.update({
  id: '/api/admin/bootstrap',
  path: '/api/admin/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTicketsIdRoute = AdminTicketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminTicketsRoute,
} as any)
const AdminQuotesIdRoute = AdminQuotesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminQuotesRoute,
} as any)
const AdminLeadsIdRoute = AdminLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminLeadsRoute,
} as any)
const AdminInvoicesIdRoute = AdminInvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminInvoicesRoute,
} as any)
const AdminCreditNotesIdRoute = AdminCreditNotesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCreditNotesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/care-plans': typeof CarePlansRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/demos': typeof DemosRoute
  '/free-audit': typeof FreeAuditRoute
  '/login': typeof LoginRoute
  '/memberships': typeof MembershipsRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/services': typeof ServicesRoute
  '/admin/chats': typeof AdminChatsRoute
  '/admin/credit-notes': typeof AdminCreditNotesRouteWithChildren
  '/admin/invoices': typeof AdminInvoicesRouteWithChildren
  '/admin/leads': typeof AdminLeadsRouteWithChildren
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/quotes': typeof AdminQuotesRouteWithChildren
  '/admin/tickets': typeof AdminTicketsRouteWithChildren
  '/api/blog-pdf': typeof ApiBlogPdfRoute
  '/api/quote': typeof ApiQuoteRoute
  '/api/send-doc': typeof ApiSendDocRoute
  '/api/track': typeof ApiTrackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/failed': typeof CheckoutFailedRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/service-agreement': typeof LegalServiceAgreementRoute
  '/legal/terms': typeof LegalTermsRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/credit-notes/$id': typeof AdminCreditNotesIdRoute
  '/admin/invoices/$id': typeof AdminInvoicesIdRoute
  '/admin/leads/$id': typeof AdminLeadsIdRoute
  '/admin/quotes/$id': typeof AdminQuotesIdRoute
  '/admin/tickets/$id': typeof AdminTicketsIdRoute
  '/api/admin/bootstrap': typeof ApiAdminBootstrapRoute
  '/api/admin/check-role': typeof ApiAdminCheckRoleRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/payfast/checkout': typeof ApiPayfastCheckoutRoute
  '/api/payfast/notify': typeof ApiPayfastNotifyRoute
  '/api/yoco/checkout': typeof ApiYocoCheckoutRoute
  '/api/yoco/webhook': typeof ApiYocoWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/care-plans': typeof CarePlansRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/demos': typeof DemosRoute
  '/free-audit': typeof FreeAuditRoute
  '/login': typeof LoginRoute
  '/memberships': typeof MembershipsRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/services': typeof ServicesRoute
  '/admin/chats': typeof AdminChatsRoute
  '/admin/credit-notes': typeof AdminCreditNotesRouteWithChildren
  '/admin/invoices': typeof AdminInvoicesRouteWithChildren
  '/admin/leads': typeof AdminLeadsRouteWithChildren
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/quotes': typeof AdminQuotesRouteWithChildren
  '/admin/tickets': typeof AdminTicketsRouteWithChildren
  '/api/blog-pdf': typeof ApiBlogPdfRoute
  '/api/quote': typeof ApiQuoteRoute
  '/api/send-doc': typeof ApiSendDocRoute
  '/api/track': typeof ApiTrackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/failed': typeof CheckoutFailedRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/service-agreement': typeof LegalServiceAgreementRoute
  '/legal/terms': typeof LegalTermsRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/admin/credit-notes/$id': typeof AdminCreditNotesIdRoute
  '/admin/invoices/$id': typeof AdminInvoicesIdRoute
  '/admin/leads/$id': typeof AdminLeadsIdRoute
  '/admin/quotes/$id': typeof AdminQuotesIdRoute
  '/admin/tickets/$id': typeof AdminTicketsIdRoute
  '/api/admin/bootstrap': typeof ApiAdminBootstrapRoute
  '/api/admin/check-role': typeof ApiAdminCheckRoleRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/payfast/checkout': typeof ApiPayfastCheckoutRoute
  '/api/payfast/notify': typeof ApiPayfastNotifyRoute
  '/api/yoco/checkout': typeof ApiYocoCheckoutRoute
  '/api/yoco/webhook': typeof ApiYocoWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/care-plans': typeof CarePlansRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/demos': typeof DemosRoute
  '/free-audit': typeof FreeAuditRoute
  '/login': typeof LoginRoute
  '/memberships': typeof MembershipsRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/services': typeof ServicesRoute
  '/admin/chats': typeof AdminChatsRoute
  '/admin/credit-notes': typeof AdminCreditNotesRouteWithChildren
  '/admin/invoices': typeof AdminInvoicesRouteWithChildren
  '/admin/leads': typeof AdminLeadsRouteWithChildren
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/quotes': typeof AdminQuotesRouteWithChildren
  '/admin/tickets': typeof AdminTicketsRouteWithChildren
  '/api/blog-pdf': typeof ApiBlogPdfRoute
  '/api/quote': typeof ApiQuoteRoute
  '/api/send-doc': typeof ApiSendDocRoute
  '/api/track': typeof ApiTrackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/failed': typeof CheckoutFailedRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/service-agreement': typeof LegalServiceAgreementRoute
  '/legal/terms': typeof LegalTermsRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/credit-notes/$id': typeof AdminCreditNotesIdRoute
  '/admin/invoices/$id': typeof AdminInvoicesIdRoute
  '/admin/leads/$id': typeof AdminLeadsIdRoute
  '/admin/quotes/$id': typeof AdminQuotesIdRoute
  '/admin/tickets/$id': typeof AdminTicketsIdRoute
  '/api/admin/bootstrap': typeof ApiAdminBootstrapRoute
  '/api/admin/check-role': typeof ApiAdminCheckRoleRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/payfast/checkout': typeof ApiPayfastCheckoutRoute
  '/api/payfast/notify': typeof ApiPayfastNotifyRoute
  '/api/yoco/checkout': typeof ApiYocoCheckoutRoute
  '/api/yoco/webhook': typeof ApiYocoWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/care-plans'
    | '/chat'
    | '/contact'
    | '/demos'
    | '/free-audit'
    | '/login'
    | '/memberships'
    | '/portfolio'
    | '/pricing'
    | '/products'
    | '/services'
    | '/admin/chats'
    | '/admin/credit-notes'
    | '/admin/invoices'
    | '/admin/leads'
    | '/admin/memberships'
    | '/admin/products'
    | '/admin/quotes'
    | '/admin/tickets'
    | '/api/blog-pdf'
    | '/api/quote'
    | '/api/send-doc'
    | '/api/track'
    | '/blog/$slug'
    | '/checkout/failed'
    | '/checkout/success'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/service-agreement'
    | '/legal/terms'
    | '/admin/'
    | '/blog/'
    | '/admin/credit-notes/$id'
    | '/admin/invoices/$id'
    | '/admin/leads/$id'
    | '/admin/quotes/$id'
    | '/admin/tickets/$id'
    | '/api/admin/bootstrap'
    | '/api/admin/check-role'
    | '/api/auth/signup'
    | '/api/payfast/checkout'
    | '/api/payfast/notify'
    | '/api/yoco/checkout'
    | '/api/yoco/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/care-plans'
    | '/chat'
    | '/contact'
    | '/demos'
    | '/free-audit'
    | '/login'
    | '/memberships'
    | '/portfolio'
    | '/pricing'
    | '/products'
    | '/services'
    | '/admin/chats'
    | '/admin/credit-notes'
    | '/admin/invoices'
    | '/admin/leads'
    | '/admin/memberships'
    | '/admin/products'
    | '/admin/quotes'
    | '/admin/tickets'
    | '/api/blog-pdf'
    | '/api/quote'
    | '/api/send-doc'
    | '/api/track'
    | '/blog/$slug'
    | '/checkout/failed'
    | '/checkout/success'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/service-agreement'
    | '/legal/terms'
    | '/admin'
    | '/blog'
    | '/admin/credit-notes/$id'
    | '/admin/invoices/$id'
    | '/admin/leads/$id'
    | '/admin/quotes/$id'
    | '/admin/tickets/$id'
    | '/api/admin/bootstrap'
    | '/api/admin/check-role'
    | '/api/auth/signup'
    | '/api/payfast/checkout'
    | '/api/payfast/notify'
    | '/api/yoco/checkout'
    | '/api/yoco/webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/care-plans'
    | '/chat'
    | '/contact'
    | '/demos'
    | '/free-audit'
    | '/login'
    | '/memberships'
    | '/portfolio'
    | '/pricing'
    | '/products'
    | '/services'
    | '/admin/chats'
    | '/admin/credit-notes'
    | '/admin/invoices'
    | '/admin/leads'
    | '/admin/memberships'
    | '/admin/products'
    | '/admin/quotes'
    | '/admin/tickets'
    | '/api/blog-pdf'
    | '/api/quote'
    | '/api/send-doc'
    | '/api/track'
    | '/blog/$slug'
    | '/checkout/failed'
    | '/checkout/success'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/service-agreement'
    | '/legal/terms'
    | '/admin/'
    | '/blog/'
    | '/admin/credit-notes/$id'
    | '/admin/invoices/$id'
    | '/admin/leads/$id'
    | '/admin/quotes/$id'
    | '/admin/tickets/$id'
    | '/api/admin/bootstrap'
    | '/api/admin/check-role'
    | '/api/auth/signup'
    | '/api/payfast/checkout'
    | '/api/payfast/notify'
    | '/api/yoco/checkout'
    | '/api/yoco/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  CarePlansRoute: typeof CarePlansRoute
  ChatRoute: typeof ChatRoute
  ContactRoute: typeof ContactRoute
  DemosRoute: typeof DemosRoute
  FreeAuditRoute: typeof FreeAuditRoute
  LoginRoute: typeof LoginRoute
  MembershipsRoute: typeof MembershipsRoute
  PortfolioRoute: typeof PortfolioRoute
  PricingRoute: typeof PricingRoute
  ProductsRoute: typeof ProductsRoute
  ServicesRoute: typeof ServicesRoute
  ApiBlogPdfRoute: typeof ApiBlogPdfRoute
  ApiQuoteRoute: typeof ApiQuoteRoute
  ApiSendDocRoute: typeof ApiSendDocRoute
  ApiTrackRoute: typeof ApiTrackRoute
  CheckoutFailedRoute: typeof CheckoutFailedRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundRoute: typeof LegalRefundRoute
  LegalServiceAgreementRoute: typeof LegalServiceAgreementRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ApiAdminBootstrapRoute: typeof ApiAdminBootstrapRoute
  ApiAdminCheckRoleRoute: typeof ApiAdminCheckRoleRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  ApiPayfastCheckoutRoute: typeof ApiPayfastCheckoutRoute
  ApiPayfastNotifyRoute: typeof ApiPayfastNotifyRoute
  ApiYocoCheckoutRoute: typeof ApiYocoCheckoutRoute
  ApiYocoWebhookRoute: typeof ApiYocoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memberships': {
      id: '/memberships'
      path: '/memberships'
      fullPath: '/memberships'
      preLoaderRoute: typeof MembershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-audit': {
      id: '/free-audit'
      path: '/free-audit'
      fullPath: '/free-audit'
      preLoaderRoute: typeof FreeAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos': {
      id: '/demos'
      path: '/demos'
      fullPath: '/demos'
      preLoaderRoute: typeof DemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care-plans': {
      id: '/care-plans'
      path: '/care-plans'
      fullPath: '/care-plans'
      preLoaderRoute: typeof CarePlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/service-agreement': {
      id: '/legal/service-agreement'
      path: '/legal/service-agreement'
      fullPath: '/legal/service-agreement'
      preLoaderRoute: typeof LegalServiceAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refund': {
      id: '/legal/refund'
      path: '/legal/refund'
      fullPath: '/legal/refund'
      preLoaderRoute: typeof LegalRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/failed': {
      id: '/checkout/failed'
      path: '/checkout/failed'
      fullPath: '/checkout/failed'
      preLoaderRoute: typeof CheckoutFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/track': {
      id: '/api/track'
      path: '/api/track'
      fullPath: '/api/track'
      preLoaderRoute: typeof ApiTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-doc': {
      id: '/api/send-doc'
      path: '/api/send-doc'
      fullPath: '/api/send-doc'
      preLoaderRoute: typeof ApiSendDocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quote': {
      id: '/api/quote'
      path: '/api/quote'
      fullPath: '/api/quote'
      preLoaderRoute: typeof ApiQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog-pdf': {
      id: '/api/blog-pdf'
      path: '/api/blog-pdf'
      fullPath: '/api/blog-pdf'
      preLoaderRoute: typeof ApiBlogPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotes': {
      id: '/admin/quotes'
      path: '/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AdminQuotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/memberships': {
      id: '/admin/memberships'
      path: '/memberships'
      fullPath: '/admin/memberships'
      preLoaderRoute: typeof AdminMembershipsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/credit-notes': {
      id: '/admin/credit-notes'
      path: '/credit-notes'
      fullPath: '/admin/credit-notes'
      preLoaderRoute: typeof AdminCreditNotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chats': {
      id: '/admin/chats'
      path: '/chats'
      fullPath: '/admin/chats'
      preLoaderRoute: typeof AdminChatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/yoco/webhook': {
      id: '/api/yoco/webhook'
      path: '/api/yoco/webhook'
      fullPath: '/api/yoco/webhook'
      preLoaderRoute: typeof ApiYocoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/yoco/checkout': {
      id: '/api/yoco/checkout'
      path: '/api/yoco/checkout'
      fullPath: '/api/yoco/checkout'
      preLoaderRoute: typeof ApiYocoCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payfast/notify': {
      id: '/api/payfast/notify'
      path: '/api/payfast/notify'
      fullPath: '/api/payfast/notify'
      preLoaderRoute: typeof ApiPayfastNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payfast/checkout': {
      id: '/api/payfast/checkout'
      path: '/api/payfast/checkout'
      fullPath: '/api/payfast/checkout'
      preLoaderRoute: typeof ApiPayfastCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/check-role': {
      id: '/api/admin/check-role'
      path: '/api/admin/check-role'
      fullPath: '/api/admin/check-role'
      preLoaderRoute: typeof ApiAdminCheckRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/bootstrap': {
      id: '/api/admin/bootstrap'
      path: '/api/admin/bootstrap'
      fullPath: '/api/admin/bootstrap'
      preLoaderRoute: typeof ApiAdminBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tickets/$id': {
      id: '/admin/tickets/$id'
      path: '/$id'
      fullPath: '/admin/tickets/$id'
      preLoaderRoute: typeof AdminTicketsIdRouteImport
      parentRoute: typeof AdminTicketsRoute
    }
    '/admin/quotes/$id': {
      id: '/admin/quotes/$id'
      path: '/$id'
      fullPath: '/admin/quotes/$id'
      preLoaderRoute: typeof AdminQuotesIdRouteImport
      parentRoute: typeof AdminQuotesRoute
    }
    '/admin/leads/$id': {
      id: '/admin/leads/$id'
      path: '/$id'
      fullPath: '/admin/leads/$id'
      preLoaderRoute: typeof AdminLeadsIdRouteImport
      parentRoute: typeof AdminLeadsRoute
    }
    '/admin/invoices/$id': {
      id: '/admin/invoices/$id'
      path: '/$id'
      fullPath: '/admin/invoices/$id'
      preLoaderRoute: typeof AdminInvoicesIdRouteImport
      parentRoute: typeof AdminInvoicesRoute
    }
    '/admin/credit-notes/$id': {
      id: '/admin/credit-notes/$id'
      path: '/$id'
      fullPath: '/admin/credit-notes/$id'
      preLoaderRoute: typeof AdminCreditNotesIdRouteImport
      parentRoute: typeof AdminCreditNotesRoute
    }
  }
}

interface AdminCreditNotesRouteChildren {
  AdminCreditNotesIdRoute: typeof AdminCreditNotesIdRoute
}

const AdminCreditNotesRouteChildren: AdminCreditNotesRouteChildren = {
  AdminCreditNotesIdRoute: AdminCreditNotesIdRoute,
}

const AdminCreditNotesRouteWithChildren =
  AdminCreditNotesRoute._addFileChildren(AdminCreditNotesRouteChildren)

interface AdminInvoicesRouteChildren {
  AdminInvoicesIdRoute: typeof AdminInvoicesIdRoute
}

const AdminInvoicesRouteChildren: AdminInvoicesRouteChildren = {
  AdminInvoicesIdRoute: AdminInvoicesIdRoute,
}

const AdminInvoicesRouteWithChildren = AdminInvoicesRoute._addFileChildren(
  AdminInvoicesRouteChildren,
)

interface AdminLeadsRouteChildren {
  AdminLeadsIdRoute: typeof AdminLeadsIdRoute
}

const AdminLeadsRouteChildren: AdminLeadsRouteChildren = {
  AdminLeadsIdRoute: AdminLeadsIdRoute,
}

const AdminLeadsRouteWithChildren = AdminLeadsRoute._addFileChildren(
  AdminLeadsRouteChildren,
)

interface AdminQuotesRouteChildren {
  AdminQuotesIdRoute: typeof AdminQuotesIdRoute
}

const AdminQuotesRouteChildren: AdminQuotesRouteChildren = {
  AdminQuotesIdRoute: AdminQuotesIdRoute,
}

const AdminQuotesRouteWithChildren = AdminQuotesRoute._addFileChildren(
  AdminQuotesRouteChildren,
)

interface AdminTicketsRouteChildren {
  AdminTicketsIdRoute: typeof AdminTicketsIdRoute
}

const AdminTicketsRouteChildren: AdminTicketsRouteChildren = {
  AdminTicketsIdRoute: AdminTicketsIdRoute,
}

const AdminTicketsRouteWithChildren = AdminTicketsRoute._addFileChildren(
  AdminTicketsRouteChildren,
)

interface AdminRouteChildren {
  AdminChatsRoute: typeof AdminChatsRoute
  AdminCreditNotesRoute: typeof AdminCreditNotesRouteWithChildren
  AdminInvoicesRoute: typeof AdminInvoicesRouteWithChildren
  AdminLeadsRoute: typeof AdminLeadsRouteWithChildren
  AdminMembershipsRoute: typeof AdminMembershipsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminQuotesRoute: typeof AdminQuotesRouteWithChildren
  AdminTicketsRoute: typeof AdminTicketsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminChatsRoute: AdminChatsRoute,
  AdminCreditNotesRoute: AdminCreditNotesRouteWithChildren,
  AdminInvoicesRoute: AdminInvoicesRouteWithChildren,
  AdminLeadsRoute: AdminLeadsRouteWithChildren,
  AdminMembershipsRoute: AdminMembershipsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminQuotesRoute: AdminQuotesRouteWithChildren,
  AdminTicketsRoute: AdminTicketsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  CarePlansRoute: CarePlansRoute,
  ChatRoute: ChatRoute,
  ContactRoute: ContactRoute,
  DemosRoute: DemosRoute,
  FreeAuditRoute: FreeAuditRoute,
  LoginRoute: LoginRoute,
  MembershipsRoute: MembershipsRoute,
  PortfolioRoute: PortfolioRoute,
  PricingRoute: PricingRoute,
  ProductsRoute: ProductsRoute,
  ServicesRoute: ServicesRoute,
  ApiBlogPdfRoute: ApiBlogPdfRoute,
  ApiQuoteRoute: ApiQuoteRoute,
  ApiSendDocRoute: ApiSendDocRoute,
  ApiTrackRoute: ApiTrackRoute,
  CheckoutFailedRoute: CheckoutFailedRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundRoute: LegalRefundRoute,
  LegalServiceAgreementRoute: LegalServiceAgreementRoute,
  LegalTermsRoute: LegalTermsRoute,
  ApiAdminBootstrapRoute: ApiAdminBootstrapRoute,
  ApiAdminCheckRoleRoute: ApiAdminCheckRoleRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  ApiPayfastCheckoutRoute: ApiPayfastCheckoutRoute,
  ApiPayfastNotifyRoute: ApiPayfastNotifyRoute,
  ApiYocoCheckoutRoute: ApiYocoCheckoutRoute,
  ApiYocoWebhookRoute: ApiYocoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
